base_dockerfile_template: |
  ARG JAVA_VERSION=""

  FROM openjdk:${{JAVA_VERSION}}-slim

  MAINTAINER Mutlu Polatcan <mutlupolatcan@gmail.com>

  ARG HADOOP_VERSION=""
  ARG HADOOP_DOWNLOAD_LINK="http://www-eu.apache.org/dist/hadoop/common/hadoop-${{HADOOP_VERSION}}/hadoop-${{HADOOP_VERSION}}.tar.gz"

  ENV HDUSER_HOME "/home/hduser"
  ENV HBASE_HOME="${{HDUSER_HOME}}/hbase" \
      PHOENIX_HOME="${{HDUSER_HOME}}/phoenix" \
      HADOOP_NATIVE_LIBS_HOME="${{HDUSER_HOME}}/hadoop_native_libs" \
      LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${{HADOOP_NATIVE_LIBS_HOME}}
  ENV HBASE_CONF_DIR="${{HBASE_HOME}}/conf" \
      PATH=$PATH:${{HBASE_HOME}}/bin:${{PHOENIX_HOME}}/bin \
      HBASE_DAEMONS="NULL" \
      HBASE_MANAGES_ZK="false" \
      HBASE_HEAP_SIZE="NULL" \
      HBASE_OFFHEAP_SIZE="NULL" \
      DFS_NAMENODE_CONN_RETRY_INTERVAL="5" \
  {env_vars}

  ADD entrypoint.sh ${{HDUSER_HOME}}/hbase_entrypoint.sh
  ADD config_loader.sh ${{HDUSER_HOME}}/hbase_config_loader.sh

  RUN apt-get update && \
      apt-get -y install --no-install-recommends procps \
                                                 nano \
                                                 wget \
                                                 rsync \
                                                 gcc \
                                                 g++ \
                                                 unzip \
                                                 iputils-ping \
                                                 telnet \
                                                 netcat \
                                                 net-tools \
                                                 python && \
      rm -rf /var/lib/apt/lists/* && \
      addgroup hadoop && adduser --disabled-password --gecos "" --ingroup hadoop hduser && \
      mkdir -p ${{HBASE_HOME}} ${{PHOENIX_HOME}} ${{HADOOP_NATIVE_LIBS_HOME}} && \
      wget ${{HADOOP_DOWNLOAD_LINK}} && \
      tar -xvzf hadoop-${{HADOOP_VERSION}}.tar.gz -C ${{HDUSER_HOME}} && \
      mv ${{HDUSER_HOME}}/hadoop-${{HADOOP_VERSION}}/lib/native/* ${{HADOOP_NATIVE_LIBS_HOME}} && \
      mv ${{HDUSER_HOME}}/hadoop-${{HADOOP_VERSION}}/share/hadoop/common/*.jar ${{HBASE_HOME}}/lib && \
      mv ${{HDUSER_HOME}}/hadoop-${{HADOOP_VERSION}}/share/hadoop/common/lib/*.jar ${{HBASE_HOME}}/lib && \
      rm -r ${{HDUSER_HOME}}/hadoop-${{HADOOP_VERSION}} && \
      rm hadoop-${{HADOOP_VERSION}}.tar.gz && \
      mkdir -p ${{HBASE_HOME}} ${{PHOENIX_HOME}} && \
      chown -R hduser:hadoop ${{HDUSER_HOME}} && \
      chmod +x ${{HDUSER_HOME}}/hbase_entrypoint.sh ${{HDUSER_HOME}}/hbase_config_loader.sh


config_loader_sh_template: |
  #!/usr/bin/env bash

  function load_config() {{
      if [[ "$2" != "NULL" ]]
          then
              printf "\t<property>\n\t\t<name>$1</name>\n\t\t<value>$2</value>\n\t</property>\n" >> "${{HBASE_CONF_DIR}}/$3"
      fi
  }}

  function load_config_with_opt() {{
      if [[ "$2" != "NULL" ]]
          then
              printf "\t<property>\n\t\t<name>$1</name>\n\t\t<value>$3</value>\n\t</property>\n" >> "${{HBASE_CONF_DIR}}/$5"
      else
          printf "\t<property>\n\t\t<name>$1</name>\n\t\t<value>$4</value>\n\t</property>\n" >> "${{HBASE_CONF_DIR}}/$5"
      fi
  }}

  {load_fn_calls}

config_files:
  - path: hbase_configs/hbase-site.yml
    filename: hbase-site.xml

output_dir: ../../base