version: "3"
services:
  hbase-master:
    image: mpolatcan/hbase:2.2.2-java8
    container_name: hbase-master
    hostname: hbase-master
    environment:
      HBASE_DAEMONS: |
        master

  hbase-regionserver:
    image: mpolatcan/hbase:2.2.2-java8
    environment:
      HBASE_DAEMONS: |
        regionserver

  hdfs-master:
    image: mpolatcan/hadoop:3.2.1-java8
    container_name: hdfs-master
    hostname: hdfs-master
    environment:
      HADOOP_DAEMONS: |
          namenode
          secondarynamenode
          resourcemanager
      YARN_SCHEDULER_MINIMUM_ALLOCATION_MB: "128"
      YARN_SCHEDULER_MAXIMUM_ALLOCATION_MB: "1536"
    ports:
      - 9870:9870 # Namenode UI
      - 9868:9868 # Secondarynamenode UI Port
      - 8088:8088 # Resourcemanager UI Port

  hdfs-slave:
    image: mpolatcan/hadoop:3.2.1-java8
    environment:
      HADOOP_DAEMONS: |
          datanode
          nodemanager
      DFS_NAMENODE_HOSTNAME: "hdfs-master"
      YARN_RESOURCEMANAGER_HOSTNAME: "hdfs-master"
      YARN_NODEMANAGER_RESOURCE_MEMORY_MB: "1536"
      YARN_NODEMANAGER_RESOURCE_CPU_VCORES: "2"
    ports:
      - 9864 # Datanode UI Port
      - 8042 # Nodemanager UI Port
    depends_on:
      - hdfs-master