version: "3"
services:
  hbase-master:
    image: mpolatcan/hbase:2.2.2-java8
    container_name: hbase-master
    hostname: hbase-master
    environment:
      HBASE_DAEMONS: |
        master
        thrift
        rest
      DFS_NAMENODE_HOSTNAME: "hdfs-master"
      HBASE_ZOOKEEPER_QUORUM: "zk1,zk2,zk3"
    ports:
      - 16010:16010
      - 8765:8765

  hbase-regionserver:
    image: mpolatcan/hbase:2.2.2-java8
    environment:
      HBASE_DAEMONS: |
        regionserver
      DFS_NAMENODE_HOSTNAME: "hdfs-master"
      HBASE_MASTER_HOSTNAME: "hbase-master"
      HBASE_ZOOKEEPER_QUORUM: "zk1,zk2,zk3"

  hdfs-master:
    image: mpolatcan/hadoop:3.2.1-java8
    container_name: hdfs-master
    hostname: hdfs-master
    environment:
      HADOOP_DAEMONS: |
        namenode
    ports:
      - 9870:9870 # Namenode UI
      - 9868:9868 # Secondarynamenode UI Port
      - 8088:8088 # Resourcemanager UI Port

  hdfs-slave:
    image: mpolatcan/hadoop:3.2.1-java8
    environment:
      HADOOP_DAEMONS: |
        datanode
      DFS_NAMENODE_HOSTNAME: "hdfs-master"
    ports:
      - 9864 # Datanode UI Port
      - 8042 # Nodemanager UI Port

  # -------------------------------- ZOOKEEPER QUORUM ------------------------------------------
  zk1:
    image: zookeeper
    restart: always
    container_name: zk1
    hostname: zk1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: "1"
      ZOO_SERVERS: "server.1=0.0.0.0:2888:3888;2181 server.2=zk2:2888:3888;2181 server.3=zk3:2888:3888;2181"

  zk2:
    image: zookeeper
    restart: always
    hostname: zk2
    container_name: zk2
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: "2"
      ZOO_SERVERS: "server.1=zk1:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181 server.3=zk3:2888:3888;2181"

  zk3:
    image: zookeeper
    restart: always
    hostname: zk3
    container_name: zk3
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: "3"
      ZOO_SERVERS: "server.1=zk1:2888:3888;2181 server.2=zk2:2888:3888;2181 server.3=0.0.0.0:2888:3888;2181"
  # -------------------------------------------------------------------------------------------