name: hbase-docker

on:
  push:
    branches:
      - master

jobs:
  build-base-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repository: [hbase]
        java_version: [8]
        htrace_version: [3.2.0]
        hadoop_version: [3.2.1, 3.1.4, 2.10.1, 2.9.2, 2.8.5, 2.7.7]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - run: |
          python -m pip install --upgrade pip
          pip install pyyaml
      - run: |
          cd src/base
          python config_loader_generator.py config.yaml
      - run: echo ${{secrets.DOCKER_PASSWORD}} | docker login -u ${{secrets.DOCKER_USERNAME}} --password-stdin
      - run: docker build -q
          -t ${{secrets.DOCKER_USERNAME}}/${{matrix.repository}}:base-hadoop-${{matrix.hadoop_version}}-java${{matrix.java_version}}
          --build-arg HADOOP_VERSION=${{matrix.hadoop_version}}
          --build-arg HTRACE_VERSION=${{matrix.htrace_version}}
          --build-arg JAVA_VERSION=${{matrix.java_version}}
          src/base
      - run: docker push ${{secrets.DOCKER_USERNAME}}/${{matrix.repository}}:base-hadoop-${{matrix.hadoop_version}}-java${{matrix.java_version}}
      - run: docker rmi ${{secrets.DOCKER_USERNAME}}/${{matrix.repository}}:base-hadoop-${{matrix.hadoop_version}}-java${{matrix.java_version}}

  build-setup-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repository: [hbase]
        java_version: [8]
        phoenix_version: [5.0.0]
        phoenix_hbase_version: ["2.0"]
        hbase_version: [2.3.2, 2.2.6, 1.4.13]
        hadoop_version: [3.2.1, 3.1.4, 2.10.1, 2.9.2, 2.8.5, 2.7.7]
        exclude:
          - hbase_version: 1.4.13
            hadoop_version: 2.8.5
          - hbase_version: 1.4.13
            hadoop_version: 2.9.2
          - hbase_version: 1.4.13
            hadoop_version: 2.10.1
          - hbase_version: 1.4.13
            hadoop_version: 3.1.4
          - hbase_version: 1.4.13
            hadoop_version: 3.2.1
          - hbase_version: 1.4.13
            hadoop_version: 3.3.0
          - hbase_version: 2.2.6
            hadoop_version: 2.7.7
          - hbase_version: 2.2.6
            hadoop_version: 2.10.1
          - hbase_version: 2.3.2
            hadoop_version: 2.7.7
          - hbase_version: 2.3.2
            hadoop_version: 2.8.5
          - hbase_version: 2.3.2
            hadoop_version: 2.9.2
    needs: build-base-image
    steps:
      - uses: actions/checkout@v1
      - run: echo ${{secrets.DOCKER_PASSWORD}} | docker login -u ${{secrets.DOCKER_USERNAME}} --password-stdin
      - run: docker build -q
          -t ${{secrets.DOCKER_USERNAME}}/${{matrix.repository}}:${{matrix.hbase_version}}-hadoop-${{matrix.hadoop_version}}-java${{matrix.java_version}}
          --build-arg HADOOP_VERSION=${{matrix.hadoop_version}}
          --build-arg HBASE_VERSION=${{matrix.hbase_version}}
          --build-arg PHOENIX_VERSION=${{matrix.phoenix_version}}
          --build-arg PHOENIX_HBASE_VERSION=${{matrix.phoenix_hbase_version}}
          --build-arg JAVA_VERSION=${{matrix.java_version}}
          src/setup
      - run: docker push ${{secrets.DOCKER_USERNAME}}/${{matrix.repository}}:${{matrix.hbase_version}}-hadoop-${{matrix.hadoop_version}}-java${{matrix.java_version}}
      - run: docker rmi ${{secrets.DOCKER_USERNAME}}/${{matrix.repository}}:${{matrix.hbase_version}}-hadoop-${{matrix.hadoop_version}}-java${{matrix.java_version}}